//! Polynomial arithmetic over `F_p2`, including the FFT that Loquat runs
//! on multiplicative cosets.
//!
//! Coefficients are stored lowest-degree-first.
//!
//! Reference: this is the machinery under the paper's univariate sumcheck
//! (§3.2), which Loquat takes from Aurora — Ben-Sasson, Chiesa, Riabzev,
//! Spooner, Virza, Ward (EUROCRYPT 2019), the paper's [11].

use crate::field::{subgroup_generator, Fp2};

/// Evaluates a polynomial at a single point by Horner's rule.
pub fn evaluate_at(coefficients: &[Fp2], x: Fp2) -> Fp2 {
    let mut result = Fp2::ZERO;
    for coefficient in coefficients.iter().rev() {
        result = result * x + *coefficient;
    }
    result
}

fn bit_reverse_permute(values: &mut [Fp2]) {
    let n = values.len();
    let mut target = 0usize;
    for source in 1..n {
        let mut bit = n >> 1;
        while target & bit != 0 {
            target ^= bit;
            bit >>= 1;
        }
        target |= bit;
        if source < target {
            values.swap(source, target);
        }
    }
}

/// In-place number-theoretic transform over the subgroup generated by
/// `generator`, which must have order exactly `values.len()`.
fn ntt(values: &mut [Fp2], generator: Fp2) {
    let n = values.len();
    assert!(n.is_power_of_two(), "NTT size must be a power of two");
    if n == 1 {
        return;
    }
    bit_reverse_permute(values);

    let mut length = 2;
    // `generator` has order n; the root for a block of size `length` is
    // generator^(n/length).
    while length <= n {
        let step = generator.pow((n / length) as u128);
        for block in values.chunks_mut(length) {
            let mut twiddle = Fp2::ONE;
            for offset in 0..length / 2 {
                let even = block[offset];
                let odd = block[offset + length / 2] * twiddle;
                block[offset] = even + odd;
                block[offset + length / 2] = even - odd;
                twiddle = twiddle * step;
            }
        }
        length *= 2;
    }
}

/// Evaluates `coefficients` over the coset `{shift * w^i}` where `w`
/// generates a subgroup of size `2^log_size`.
///
/// The trick: evaluating `f` at `shift * w^i` is the same as evaluating
/// `g(x) = f(shift * x)` at `w^i`, and `g`'s coefficients are just `f`'s
/// scaled by powers of `shift`.
pub fn evaluate_over_coset(coefficients: &[Fp2], shift: Fp2, log_size: u32) -> Vec<Fp2> {
    let size = 1usize << log_size;
    assert!(coefficients.len() <= size, "polynomial degree exceeds coset size");

    let mut scaled = vec![Fp2::ZERO; size];
    let mut power = Fp2::ONE;
    for (i, coefficient) in coefficients.iter().enumerate() {
        scaled[i] = *coefficient * power;
        power = power * shift;
    }

    ntt(&mut scaled, subgroup_generator(log_size));
    scaled
}

/// Recovers coefficients from evaluations over the coset `{shift * w^i}`.
pub fn interpolate_over_coset(values: &[Fp2], shift: Fp2, log_size: u32) -> Vec<Fp2> {
    let size = 1usize << log_size;
    assert_eq!(values.len(), size, "need exactly one value per coset point");

    let mut coefficients = values.to_vec();
    // Inverse NTT: transform with the inverse generator, then scale by 1/n.
    let generator = subgroup_generator(log_size);
    ntt(&mut coefficients, generator.inverse().expect("generator is non-zero"));

    let size_inverse = Fp2::from_base(crate::field::Fp::new(size as u128))
        .inverse()
        .expect("size is non-zero in this field");
    for coefficient in coefficients.iter_mut() {
        *coefficient = *coefficient * size_inverse;
    }

    // Undo the shift scaling applied during evaluation.
    let shift_inverse = shift.inverse().expect("coset shift must be non-zero");
    let mut power = Fp2::ONE;
    for coefficient in coefficients.iter_mut() {
        *coefficient = *coefficient * power;
        power = power * shift_inverse;
    }

    coefficients
}

pub fn add(a: &[Fp2], b: &[Fp2]) -> Vec<Fp2> {
    let mut result = vec![Fp2::ZERO; a.len().max(b.len())];
    for (i, value) in a.iter().enumerate() {
        result[i] = result[i] + *value;
    }
    for (i, value) in b.iter().enumerate() {
        result[i] = result[i] + *value;
    }
    result
}

pub fn scale(coefficients: &[Fp2], factor: Fp2) -> Vec<Fp2> {
    coefficients.iter().map(|c| *c * factor).collect()
}

/// Schoolbook multiplication. Degrees here stay in the low hundreds, so
/// this is not worth doing by FFT.
pub fn multiply(a: &[Fp2], b: &[Fp2]) -> Vec<Fp2> {
    if a.is_empty() || b.is_empty() {
        return Vec::new();
    }
    let mut result = vec![Fp2::ZERO; a.len() + b.len() - 1];
    for (i, x) in a.iter().enumerate() {
        if x.is_zero() {
            continue;
        }
        for (j, y) in b.iter().enumerate() {
            result[i + j] = result[i + j] + *x * *y;
        }
    }
    result
}

/// Divides by the vanishing polynomial of a coset, `Z(x) = x^size - offset`.
///
/// Returns `(quotient, remainder)` with `f = quotient * Z + remainder` and
/// `deg(remainder) < size`. Synthetic division: each time a top
/// coefficient is pushed into the quotient, it feeds back scaled by
/// `offset`, because `x^size = offset` modulo `Z`.
pub fn divide_by_vanishing(f: &[Fp2], size: usize, offset: Fp2) -> (Vec<Fp2>, Vec<Fp2>) {
    if f.len() <= size {
        return (Vec::new(), f.to_vec());
    }
    let mut working = f.to_vec();
    let mut quotient = vec![Fp2::ZERO; f.len() - size];

    for index in (size..working.len()).rev() {
        let top = working[index];
        if top.is_zero() {
            continue;
        }
        quotient[index - size] = quotient[index - size] + top;
        working[index - size] = working[index - size] + top * offset;
        working[index] = Fp2::ZERO;
    }

    working.truncate(size);
    (quotient, working)
}

/// The vanishing polynomial of the coset `{shift * w^i}` of size `size` is
/// `x^size - shift^size`. This returns that `shift^size` offset.
pub fn vanishing_offset(shift: Fp2, size: usize) -> Fp2 {
    shift.pow(size as u128)
}

/// Removes trailing zero coefficients so `len()` reflects the real degree.
pub fn trim(coefficients: &mut Vec<Fp2>) {
    while coefficients.last().map(|c| c.is_zero()).unwrap_or(false) {
        coefficients.pop();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::field::{subgroup_generator, Fp};

    fn sample_polynomial(len: usize) -> Vec<Fp2> {
        (0..len)
            .map(|i| Fp2::new(Fp::new((i as u128 + 1) * 7919), Fp::new((i as u128 + 3) * 104729)))
            .collect()
    }

    #[test]
    fn ntt_matches_naive_evaluation() {
        let log_size = 6;
        let size = 1usize << log_size;
        let coefficients = sample_polynomial(size);
        let shift = Fp2::new(Fp::new(5), Fp::new(2));

        let fast = evaluate_over_coset(&coefficients, shift, log_size);

        let generator = subgroup_generator(log_size);
        let mut point = shift;
        for value in fast.iter() {
            assert_eq!(*value, evaluate_at(&coefficients, point));
            point = point * generator;
        }
    }

    #[test]
    fn interpolation_inverts_evaluation() {
        let log_size = 6;
        let size = 1usize << log_size;
        let coefficients = sample_polynomial(size);
        let shift = Fp2::new(Fp::new(3), Fp::new(11));

        let values = evaluate_over_coset(&coefficients, shift, log_size);
        let recovered = interpolate_over_coset(&values, shift, log_size);
        assert_eq!(recovered, coefficients);
    }

    #[test]
    fn interpolation_works_for_low_degree_polynomials() {
        let log_size = 5;
        let coefficients = sample_polynomial(7);
        let shift = Fp2::new(Fp::new(9), Fp::new(4));

        let values = evaluate_over_coset(&coefficients, shift, log_size);
        let mut recovered = interpolate_over_coset(&values, shift, log_size);
        trim(&mut recovered);
        assert_eq!(recovered, coefficients);
    }

    #[test]
    fn multiplication_matches_pointwise_products() {
        let a = sample_polynomial(10);
        let b = sample_polynomial(7);
        let product = multiply(&a, &b);

        for raw in [1u128, 2, 3, 99] {
            let x = Fp2::from_base(Fp::new(raw));
            assert_eq!(evaluate_at(&product, x), evaluate_at(&a, x) * evaluate_at(&b, x));
        }
    }

    #[test]
    fn division_by_vanishing_reconstructs_the_input() {
        let size = 8;
        let shift = Fp2::new(Fp::new(6), Fp::new(1));
        let offset = vanishing_offset(shift, size);
        let f = sample_polynomial(20);

        let (quotient, remainder) = divide_by_vanishing(&f, size, offset);
        assert!(remainder.len() <= size);

        // Rebuild quotient * (x^size - offset) + remainder and compare.
        let mut vanishing = vec![Fp2::ZERO; size + 1];
        vanishing[size] = Fp2::ONE;
        vanishing[0] = -offset;
        let rebuilt = add(&multiply(&quotient, &vanishing), &remainder);

        let mut expected = f.clone();
        trim(&mut expected);
        let mut actual = rebuilt;
        trim(&mut actual);
        assert_eq!(actual, expected);
    }

    #[test]
    fn vanishing_polynomial_is_zero_on_its_coset() {
        let log_size = 4;
        let size = 1usize << log_size;
        let shift = Fp2::new(Fp::new(7), Fp::new(3));
        let offset = vanishing_offset(shift, size);

        let generator = subgroup_generator(log_size);
        let mut point = shift;
        for _ in 0..size {
            // x^size - shift^size must vanish at every coset point.
            assert_eq!(point.pow(size as u128) - offset, Fp2::ZERO);
            point = point * generator;
        }
    }
}
